apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8guard-kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8guard-kafka
    spec:
      containers:
      - name: k8guard-zookeper
        image: wurstmeister/zookeeper
      - name: k8guard-kafka
        image: wurstmeister/kafka
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "localhost:2181"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
